import { Component, OnInit, ChangeDetectionStrategy, ChangeDetectorRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { HttpClient } from '@angular/common/http';
import { environment } from '../../../../environments/environment';
import { PageHeaderComponent } from '../../../shared/components/page-header/page-header.component';
import { BreadcrumbComponent } from '../../../shared/components/breadcrumb/breadcrumb.component';
import { StatusBadgeComponent } from '../../../shared/components/status-badge/status-badge.component';
import { LoadingStateComponent } from '../../../shared/components/loading-state/loading-state.component';
import { ReportItem } from '../../../core/models/report.model';
import { ApiResponse } from '../../../core/models/api-response.model';

/**
 * Report Detail View — displays full information for a single report.
 * Fetches from the list endpoint and filters by ID (no dedicated getById endpoint yet).
 */
@Component({
  selector: 'app-report-detail',
  standalone: true,
  imports: [
    CommonModule,
    RouterLink,
    PageHeaderComponent,
    BreadcrumbComponent,
    StatusBadgeComponent,
    LoadingStateComponent
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <app-breadcrumb [items]="[
      { label: 'Home', url: '/dashboard' },
      { label: 'Reports', url: '/reports' },
      { label: item?.title ?? 'Detail' }
    ]"></app-breadcrumb>

    <app-page-header
      [title]="item?.title ?? 'Report Detail'"
      subtitle="View report configuration, parameters, and generation history">
      <a routerLink="/reports" class="btn btn-ghost btn-sm gap-2">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7" />
        </svg>
        Back to List
      </a>
    </app-page-header>

    @if (loading) {
      <app-loading-state message="Loading report details..."></app-loading-state>
    } @else if (error) {
      <div class="alert alert-error">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
        </svg>
        <span>{{ error }}</span>
        <a routerLink="/reports" class="btn btn-sm btn-ghost">Return to List</a>
      </div>
    } @else if (item) {
      <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <!-- Report Information -->
        <div class="card bg-base-100 shadow-sm">
          <div class="card-body">
            <h2 class="card-title text-lg">Report Information</h2>
            <div class="divider mt-0 mb-2"></div>
            <dl class="grid grid-cols-1 sm:grid-cols-2 gap-x-4 gap-y-3 text-sm">
              <div class="sm:col-span-2">
                <dt class="text-base-content/60 font-medium">Title</dt>
                <dd class="mt-0.5">{{ item.title }}</dd>
              </div>
              <div>
                <dt class="text-base-content/60 font-medium">Report Type</dt>
                <dd class="mt-0.5"><app-status-badge [status]="item.reportType"></app-status-badge></dd>
              </div>
              <div>
                <dt class="text-base-content/60 font-medium">Created At</dt>
                <dd class="mt-0.5">{{ item.createdAt | date:'medium' }}</dd>
              </div>
              <div class="sm:col-span-2">
                <dt class="text-base-content/60 font-medium">Description</dt>
                <dd class="mt-0.5">{{ item.description ?? '—' }}</dd>
              </div>
            </dl>
          </div>
        </div>

        <!-- Generation Details -->
        <div class="card bg-base-100 shadow-sm">
          <div class="card-body">
            <h2 class="card-title text-lg">Generation Details</h2>
            <div class="divider mt-0 mb-2"></div>
            <dl class="grid grid-cols-1 sm:grid-cols-2 gap-x-4 gap-y-3 text-sm">
              <div>
                <dt class="text-base-content/60 font-medium">Generated By</dt>
                <dd class="mt-0.5">{{ item.generatedBy ?? '—' }}</dd>
              </div>
              <div>
                <dt class="text-base-content/60 font-medium">Last Generated At</dt>
                <dd class="mt-0.5">{{ item.lastGeneratedAt ? (item.lastGeneratedAt | date:'medium') : '—' }}</dd>
              </div>
            </dl>
          </div>
        </div>

        <!-- Parameters -->
        <div class="card bg-base-100 shadow-sm lg:col-span-2">
          <div class="card-body">
            <h2 class="card-title text-lg">Parameters</h2>
            <div class="divider mt-0 mb-2"></div>
            @if (item.parameters && parameterKeys.length > 0) {
              <dl class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-x-4 gap-y-3 text-sm">
                @for (key of parameterKeys; track key) {
                  <div>
                    <dt class="text-base-content/60 font-medium">{{ formatParameterKey(key) }}</dt>
                    <dd class="mt-0.5">{{ item.parameters![key] }}</dd>
                  </div>
                }
              </dl>
            } @else {
              <p class="text-sm text-base-content/60">No parameters configured for this report.</p>
            }
          </div>
        </div>
      </div>
    }
  `
})
export class ReportDetailComponent implements OnInit {
  item: ReportItem | null = null;
  loading = true;
  error: string | null = null;
  parameterKeys: string[] = [];

  private id = '';
  private readonly apiUrl = `${environment.apiUrl}/reports`;

  constructor(
    private route: ActivatedRoute,
    private http: HttpClient,
    private cdr: ChangeDetectorRef
  ) {}

  ngOnInit(): void {
    this.id = this.route.snapshot.paramMap.get('id') ?? '';
    this.loadReport();
  }

  formatParameterKey(key: string): string {
    return key.replace(/([A-Z])/g, ' $1').replace(/^./, s => s.toUpperCase()).trim();
  }

  private loadReport(): void {
    this.http.get<ApiResponse<ReportItem[]>>(this.apiUrl).subscribe({
      next: (response) => {
        this.item = response.data.find(r => r.id === this.id) ?? null;
        if (!this.item) {
          this.error = `Report with ID "${this.id}" not found.`;
        } else if (this.item.parameters) {
          this.parameterKeys = Object.keys(this.item.parameters);
        }
        this.loading = false;
        this.cdr.markForCheck();
      },
      error: () => {
        this.error = 'Failed to load report details. Please try again.';
        this.loading = false;
        this.cdr.markForCheck();
      }
    });
  }
}
